import os

BOT_TOKEN = '7792344421:AAFD2mGg58Z51bhkqSFw5TOyd25HDVBHLfc'

CHANNEL_USERNAME = '@twelvemua'

DATABASE_URL = os.getenv("DATABASE_URL")

SHOP_ID = 'YOUR_SHOP_ID'
SHOP_SECRET_KEY = 'YOUR_SECRET_KEY'
